'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.34209
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("버들라이브러리.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        '''  속성을 재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property _7z() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7z", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property _7z64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7z64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property bl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property bm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property br() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("br", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property breadnotification() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breadnotification", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Card_Input() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Card_Input", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property checkpattern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkpattern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property checkpattern_noborder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkpattern_noborder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property close_btn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_btn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property close_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property closebtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("closebtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property ct() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ct", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property datatransfer_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("datatransfer_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property datatransfer_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("datatransfer_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property desc00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desc00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property desc01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desc01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property desc02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desc02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property DevIL_NET() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("DevIL_NET", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property easteregg_kuroneko_masturbation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("easteregg_kuroneko_masturbation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property emotion_success() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("emotion_success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property helpfont() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helpfont", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property ico_labicon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_labicon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property ico_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property ico_setting() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_setting", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property image_crushed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_crushed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property labicon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("labicon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property lf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property library_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("library_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property librarywillowslabnet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("librarywillowslabnet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property lmpico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lmpico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property lolipack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lolipack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_Checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_Checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_Checked_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_Checked_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_Checked_nb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_Checked_nb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_Checked_nb_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_Checked_nb_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_expend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_expend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_expend_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_expend_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_expend_noborder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_expend_noborder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mabi_expend_noborder_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mabi_expend_noborder_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_118() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_118", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_119() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_119", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_121() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_121", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_122() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_122", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_124() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_124", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_125() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_125", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_126() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_126", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_127() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_127", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_129() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_129", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_130() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_130", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_131() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_131", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_132() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_132", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_133() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_133", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_134() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_134", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_135() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_135", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_136() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_136", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_137() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_137", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_138() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_138", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_139() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_139", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_142() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_142", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_143() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_143", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_144() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_144", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_145() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_145", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_164() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_164", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_165() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_165", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_166() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_166", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_167() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_167", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_168() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_168", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_169() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_169", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_New() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_New", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property Mabinogi_New_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mabinogi_New_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property max() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("max", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property max_noborder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("max_noborder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property ml() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ml", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property mr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property newuser_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newuser_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property newuser_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newuser_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property newuser_normal1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newuser_normal1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property not_pined() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("not_pined", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_completedownload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_completedownload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_completefiledownload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_completefiledownload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_completeupload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_completeupload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_sync() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_sync", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property noti_warn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noti_warn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property openDir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openDir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property openDir_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openDir_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property pattern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pattern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property pined() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pined", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property pleasewait() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pleasewait", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property plfw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plfw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property progressbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("progressbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property ribon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ribon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property rt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property setting() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("setting", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property SevenZipSharp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SevenZipSharp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property startup_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("startup_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property tl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property tm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property tr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property tvn_file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvn_file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property tvn_folder_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvn_folder_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property tvn_folder_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tvn_folder_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property unpack() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("unpack", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property window_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property window_big_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_big_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property window_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property window_small_h() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("window_small_h", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Public ReadOnly Property wlab2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wlab2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
